### ISSUE TITLE
Image remains in blurred state upon reload

### ISSUE THREAD

**Issue by timarney** [revolunet/react-srcset-image#1]
Wondering if the state needs to be reset when the component unmounts.

Using Preact CLI + Preact router when I navigate to a page the initial image load is fine.  Upon navigating back to that page the image shows but is in it's blurred state. 

See:
![screenflow](https://user-images.githubusercontent.com/62242/28280892-4199ec50-6af3-11e7-9ecf-ac7780473b53.gif)

**Comment by timarney** [comment]
Update - looks like the onLoad event doesn't fire again after navigating away than back.

Looks like this issue at the browser level not this repo.

http://mikefowler.me/journal/2014/04/22/cached-images-load-event

![screen shot 2017-07-17 at 3 19 26 pm](https://user-images.githubusercontent.com/62242/28285664-97c24f9a-6b03-11e7-8f72-a7f19cabd870.png)

**Comment by revolunet** [comment]
nice anim btw :)
